
    // For MixerChannel
    // "_includes/_midi-ctrl/lcxl_mixer_auto_bind.scd".loadRelative;
    // "_includes/_midi-ctrl/lcxl_toprows_param_router.scd".loadRelative;
    // "_includes/_midi-ctrl/lcxl_mixer_bank_buttons.scd".loadRelative;
    // "_includes/_midi-ctrl/lcn_param_router.scd".loadRelative;
    // "_includes/_midi-ctrl/cc_bind_hub.scd".loadRelative;
    // ~installCCByNameRouter.();
    // ~load.();                          // loads default map path
    // ~lcxlMix[\cfg].put(\faderBottom_dB, -60);
    // ~lcxlMix[\cfg].put(\faderTop_dB,    12);
    // "_includes/panic-hook.scd".loadRelative;
