(
TempoClock.default.tempo = 110/60;
~loadSamps.("~/Music/supercollider/_samples/808s_by_SHD/808_kit/");
~loadSamps.("~/Music/supercollider/_samples/goldbaby/Cassette808/");
~loadSamps.("~/Music/supercollider/_samples/Codeine_Drum_Kit/DrumLoops/");
~loadSamps.("~/Music/supercollider/_samples/Neutron_12/");
~loadSamps.("~/Music/supercollider/_samples/_mono/jttcot/");
"fx_def.scd".loadRelative;
"pdefnA.scd".loadRelative;
"voice_def.scd".loadRelative;
"voice_pat.scd".loadRelative;
)
