///////////////////////////////////////////////////
// History, as it was on Mon May 11 13:24:17 2026.
///////////////////////////////////////////////////

// - 0:0:0.0 - (me) 
Tdef(\alt1).play(~link,  quant: 4);

// - 0:0:29.27 - (cc) 
~apcApplyParam.('b0_ds1_k3', 0.016);

// - 0:0:32.07 - (cc) 
~apcApplyParam.('b0_ds1_k1', 0.331);

// - 0:0:33.61 - (cc) 
~apcApplyParam.('b0_ds1_k1', 0.339);

// - 0:0:35.0 - (cc) 
~apcApplyParam.('b0_ds1_k5', 0.78);

// - 0:0:36.12 - (cc) 
~apcApplyParam.('b0_ds1_k6', 0.197);

// - 0:0:37.67 - (cc) 
~apcApplyParam.('b0_ds1_k6', 0.118);

// - 0:0:41.11 - (cc) 
~apcApplyParam.('b0_ds1_k4', 0.087);

// - 0:0:42.69 - (cc) 
~apcApplyParam.('b0_ds1_k4', 0.047);

// - 0:0:44.33 - (cc) 
~apcApplyParam.('b0_ds1_k4', 0.063);

// - 0:0:47.43 - (cc) 
~apcApplyParam.('b0_ds1_k5', 0.323);

// - 0:0:54.79 - (cc) 
~apcApplyParam.('b0_ds1_k3', 0.047);

