// Voice Toggles
~lpBind.([1, 1], \all, 80);                        // bottom-left pad, active bank
~lpBind.([1, 2], \v1_kit, 60);                        // bottom-left pad, active bank
~lpBind.([1, 3], \v1, 10);                        // bottom-left pad, active bank
~lpBind.([1, 4], \v2, 30);                        // bottom-left pad, active bank
~lpBind.([1, 5], \v3, 20);                        // bottom-left pad, active bank

~lpBind.([5, 1], \alt1, nil, ~link, 4);

