// LaunchControl XL (after setup if needed)
// BANK 0
// Faders
~ccBindParam.(\b0_f1, \i1, \amp, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_f2, \i2, \amp, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_f3, \i3, \amp, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_f4, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_f5, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_f6, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_f7, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_f8, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));

// Row 1 Knobs
~ccBindParam.(\b0_t1_r1, \master, \wet, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t2_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t3_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t4_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t5_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t6_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t7_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t8_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));

// Row 2 Knobs
~ccBindParam.(\b0_t1_r2, \master, \dry, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t2_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t3_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t4_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t5_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t6_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t7_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t8_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));

// Row 3 Knobs
~ccBindParam.(\b0_t1_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t2_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t3_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t4_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t5_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t6_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t7_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b0_t8_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));

// BANK 1
// Faders
~ccBindParam.(\b1_f1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_f2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_f3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_f4, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_f5, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_f6, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_f7, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_f8, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));

// Row 1 Knobs
~ccBindParam.(\b1_t1_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t2_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t3_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t4_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t5_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t6_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t7_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t8_r1, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));

// Row 2 Knobs
~ccBindParam.(\b1_t1_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t2_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t3_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t4_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t5_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t6_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t7_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t8_r2, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));

// Row 3 Knobs
~ccBindParam.(\b1_t1_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t2_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t3_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t4_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t5_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t6_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t7_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
~ccBindParam.(\b1_t8_r3, \key, \arg, ControlSpec(minval: 0.0, maxval: 1.0, warp: 'lin', step: 0.0, default: 0));
